### ISSUE TITLE
`get_version()` broken?

### ISSUE THREAD

**Issue by Jean1995** [The-Ludwig/PANAMA#73]
I've tried installing version 0.6.0 of panama, both on a Linux cluster and my local MacOS, and I get the error messages:

```
Traceback (most recent call last):
  File "/usr/local/bin/panama", line 5, in <module>
    from panama.cli import cli
  File "/usr/local/lib/python3.10/dist-packages/panama/__init__.py", line 19, in <module>
    __version__ = get_version()
  File "/usr/local/lib/python3.10/dist-packages/panama/__init__.py", line 14, in get_version
    with open(path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.10/dist-packages/pyproject.toml'
```

for Linux and

```
Traceback (most recent call last):
  File "/opt/homebrew/bin/panama", line 5, in <module>
    from panama.cli import cli
  File "/opt/homebrew/lib/python3.11/site-packages/panama/__init__.py", line 19, in <module>
    __version__ = get_version()
                  ^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/panama/__init__.py", line 14, in get_version
    with open(path) as f:
         ^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/homebrew/lib/python3.11/site-packages/pyproject.toml'
```

for MacOS.

**Comment by Jean1995** [comment]
My current "workaround" is to just comment out the line https://github.com/The-Ludwig/PANAMA/blob/main/panama/__init__.py#L19

**Comment by Jean1995** [comment]
In addition, version 0.6.0 requires the "toml" package, which doesn't seem to be installed automatically when installing panama.
